require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const CareerPath = require('../models/CareerPath');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/cpmap';

const careerPaths = [
  // ─── 1. SOFTWARE ENGINEER ────────────────────────────────────────────────────
  {
    title: 'Software Engineer',
    category: 'Engineering & Tech',
    description: 'Build software products at a tech company, starting from a CS/IT degree to professional development roles.',
    submitterName: 'Rajesh Kumar',
    submitterEmail: 'rajesh.kumar@example.com',
    submitterGender: 'Male',
    submitterEducationHistory: '10th → 12th MPC → B.Tech CSE → Working',
    submitterSkills: ['Logical thinking', 'Problem solving', 'Communication', 'Java', 'Python', 'DSA'],
    submitterBackground: 'Urban',
    submitterEconomicStatus: 'Middle',
    isSeeded: true,
    stages: [
      {
        stageName: '10th Standard',
        education: '10th (CBSE/State Board)',
        skills: ['Basic Mathematics', 'Logical Reasoning'],
        experience: 'School studies',
        livingConditions: 'Home with family',
        helpReceived: 'Teachers and family support',
        suggestions: 'Focus on Math and Science; build curiosity for computers.',
        ageRange: '14–15 years',
      },
      {
        stageName: '12th – MPC Stream',
        education: '12th (Math, Physics, Chemistry)',
        skills: ['Advanced Mathematics', 'Physics concepts', 'Analytical Thinking'],
        experience: 'Competitive exam preparation for JEE/EAPCET',
        livingConditions: 'Coaching center + home',
        helpReceived: 'Coaching institute, online resources',
        suggestions: 'Alongside board exams, start learning basic programming (C/Python).',
        ageRange: '16–17 years',
      },
      {
        stageName: 'B.Tech (CSE / IT)',
        education: 'B.Tech in Computer Science or IT (4 years)',
        skills: ['Java', 'Python', 'DSA', 'DBMS', 'OS', 'Networking', 'Git', 'Problem Solving'],
        experience: 'Internships, hackathons, open-source contributions',
        livingConditions: 'College hostel or rented PG in city',
        helpReceived: 'Faculty mentors, senior students, online platforms (LeetCode, GeeksForGeeks)',
        suggestions: 'Start DSA practice from 2nd year. Build 2–3 projects for your portfolio.',
        ageRange: '18–22 years',
      },
      {
        stageName: 'Junior Software Engineer',
        education: 'B.Tech degree (entry-level job)',
        skills: ['JavaScript', 'React/Node.js or Java Spring', 'REST APIs', 'SQL', 'Agile/Scrum'],
        experience: '0–2 years at a product/service company',
        livingConditions: 'Rented apartment in metro city',
        helpReceived: 'Senior engineers, tech leads, documentation',
        suggestions: 'Never stop learning; contribute to open source, clear your fundamentals.',
        ageRange: '22–24 years',
      },
      {
        stageName: 'Senior / Lead Engineer',
        education: 'B.Tech + 4–6 years of experience OR M.Tech/MBA',
        skills: ['System Design', 'Leadership', 'Cloud (AWS/GCP)', 'Mentoring', 'Architecture'],
        experience: '5+ years in software development',
        livingConditions: 'Owned or rented apartment',
        helpReceived: 'Professional network, conferences, online courses',
        suggestions: 'Develop soft skills equally. Consider specializations (AI, DevOps, Security).',
        ageRange: '27–30 years',
      },
    ],
    transitions: [
      {
        fromStage: '10th Standard',
        toStage: '12th – MPC Stream',
        optionsAvailable: ['12th Commerce', '12th BiPC', 'Polytechnic Diploma', 'ITI'],
        reasonChosen: 'Chose MPC to keep engineering options open, especially for JEE/EAPCET.',
        mistakes: 'Underestimated the difficulty of JEE; should have started preparation earlier.',
        advice: 'Research college entrance exams before picking your 11th stream.',
      },
      {
        fromStage: '12th – MPC Stream',
        toStage: 'B.Tech (CSE / IT)',
        optionsAvailable: ['B.Sc Computer Science', 'Diploma in CS', 'BCA', 'Direct job/freelancing'],
        reasonChosen: 'B.Tech CSE opens best placements in top tech companies and MNCs.',
        mistakes: 'Chose college only by rank, not curriculum quality. Look at placement records too.',
        advice: 'Any tier college is fine if you build skills independently. Focus on DSA and projects.',
      },
      {
        fromStage: 'B.Tech (CSE / IT)',
        toStage: 'Junior Software Engineer',
        optionsAvailable: ['Higher studies (M.Tech/MS abroad)', 'Startup', 'GATE exam', 'Teaching'],
        reasonChosen: 'Got a campus placement. Decided to gain industry experience before higher studies.',
        mistakes: 'Did not network enough during college. Attend more tech meetups and hackathons.',
        advice: 'Apply for internships from 3rd year. Practice system design from 4th year.',
      },
      {
        fromStage: 'Junior Software Engineer',
        toStage: 'Senior / Lead Engineer',
        optionsAvailable: ['MBA (IIM)', 'MS in CS abroad', 'Start own company', 'Product Manager role'],
        reasonChosen: 'Grew within the company through consistent performance and skill development.',
        mistakes: 'Stayed in comfort zone too long; should have taken challenging projects earlier.',
        advice: 'Volunteer for complex projects. Mentor juniors — teaching solidifies your knowledge.',
      },
    ],
  },

  // ─── 2. DATA SCIENTIST ───────────────────────────────────────────────────────
  {
    title: 'Data Scientist',
    category: 'Engineering & Tech',
    description: 'Analyze large datasets to derive business insights using statistical and ML techniques.',
    submitterName: 'Priya Sharma',
    submitterEmail: 'priya.sharma@example.com',
    submitterGender: 'Female',
    submitterEducationHistory: '10th → 12th MPC → B.Sc Statistics → M.Tech Data Science',
    submitterSkills: ['Analytical thinking', 'Mathematics passion', 'Pattern recognition', 'Python', 'Statistics', 'Machine Learning'],
    submitterBackground: 'Semi-Urban',
    submitterEconomicStatus: 'Middle',
    isSeeded: true,
    stages: [
      {
        stageName: '10th Standard',
        education: '10th with good Mathematics score',
        skills: ['Mathematics', 'Basic Statistics'],
        experience: 'School',
        livingConditions: 'Home',
        helpReceived: 'School teachers',
        suggestions: 'Build a strong foundation in math. Explore puzzles and data-based games.',
        ageRange: '14–15 years',
      },
      {
        stageName: '12th – MPC / Commerce with Math',
        education: '12th with Mathematics and Statistics',
        skills: ['Probability', 'Statistics', 'Calculus basics'],
        experience: 'Board exam preparation',
        livingConditions: 'Home / coaching',
        helpReceived: 'Tutors, online resources',
        suggestions: 'Take statistics and mathematics seriously—they are the core of data science.',
        ageRange: '16–17 years',
      },
      {
        stageName: 'B.Tech CSE / B.Sc Statistics or Mathematics',
        education: 'Undergraduate in CS, Statistics, or Mathematics/Physics',
        skills: ['Python', 'R', 'Linear Algebra', 'Probability', 'SQL', 'Data Wrangling'],
        experience: 'Research projects, internships, Kaggle competitions',
        livingConditions: 'Hostel / PG',
        helpReceived: 'Professors, Kaggle community, online courses (Coursera, edX)',
        suggestions: 'Start with Python and pandas. Participate in Kaggle competitions from 2nd year.',
        ageRange: '18–22 years',
      },
      {
        stageName: 'M.Sc / M.Tech in Data Science / AI',
        education: 'Postgraduate in Data Science, AI, Statistics, or related field',
        skills: ['Machine Learning', 'Deep Learning', 'NLP', 'Cloud ML', 'Research Writing'],
        experience: 'Research thesis, industry collaboration projects',
        livingConditions: 'Hostel / University housing',
        helpReceived: 'Research advisors, industry collaborations',
        suggestions: 'Pick a specialization (NLP, CV, Time Series). Publish if possible.',
        ageRange: '22–24 years',
      },
      {
        stageName: 'Data Scientist at a Tech/Analytics Firm',
        education: 'PG degree + 2–5 years experience',
        skills: ['MLOps', 'Model Deployment', 'Business Acumen', 'Communication', 'A/B Testing'],
        experience: '2–5 years in analytics / ML roles',
        livingConditions: 'Rented apartment in metro',
        helpReceived: 'Mentors, team leads, research papers',
        suggestions: 'Learn to communicate insights to non-technical stakeholders. Business context matters.',
        ageRange: '25–28 years',
      },
    ],
    transitions: [
      {
        fromStage: '10th Standard',
        toStage: '12th – MPC / Commerce with Math',
        optionsAvailable: ['12th BiPC', '12th Commerce without Math', 'Vocational'],
        reasonChosen: 'Mathematics is non-negotiable for a data science career.',
        mistakes: '',
        advice: 'Do not drop Mathematics in 12th if you are interested in data or tech fields.',
      },
      {
        fromStage: '12th – MPC / Commerce with Math',
        toStage: 'B.Tech CSE / B.Sc Statistics or Mathematics',
        optionsAvailable: ['BCA', 'Economics Honours', 'Direct job'],
        reasonChosen: 'B.Sc Statistics paired with programming gives a strong foundation.',
        mistakes: 'Avoiding CS fundamentals. You need both stats AND coding.',
        advice: 'Learn Python alongside your degree from day one.',
      },
      {
        fromStage: 'B.Tech CSE / B.Sc Statistics or Mathematics',
        toStage: 'M.Sc / M.Tech in Data Science / AI',
        optionsAvailable: ['Direct industry job as analyst', 'MS abroad', 'Certification courses only'],
        reasonChosen: 'PG adds research depth and opens doors to senior roles faster.',
        mistakes: 'Choosing PG based on brand alone; check faculty research area.',
        advice: 'Build a GitHub portfolio before applying; it matters more than GPA for industry.',
      },
      {
        fromStage: 'M.Sc / M.Tech in Data Science / AI',
        toStage: 'Data Scientist at a Tech/Analytics Firm',
        optionsAvailable: ['PhD (academia)', 'Startup founder', 'ML Engineer track'],
        reasonChosen: 'Industry offered faster real-world impact than academia at this stage.',
        mistakes: 'Not learning MLOps early; productionizing models is very different from building them.',
        advice: 'Learn Docker, APIs, and cloud platforms alongside ML algorithms.',
      },
    ],
  },

  // ─── 3. JAVA BACKEND DEVELOPER ─────────────────────────────────────────────────
  {
    title: 'Java Backend Developer',
    category: 'Engineering & Tech',
    description: 'Build scalable backend systems with Java, starting from 12th MPC and growing into enterprise application development.',
    submitterName: 'Amit Singh',
    submitterEmail: 'amit.singh@example.com',
    submitterGender: 'Male',
    submitterEducationHistory: '10th → 12th MPC → Diploma in Computer Science / B.Tech CSE → Java Backend Developer',
    submitterSkills: ['Java', 'Spring Boot', 'SQL', 'Problem solving', 'APIs', 'System design'],
    submitterBackground: 'Urban',
    submitterEconomicStatus: 'Middle',
    isSeeded: true,
    stages: [
      {
        stageName: '10th Standard',
        education: '10th with strong Mathematics and Science',
        skills: ['Math fundamentals', 'Logical reasoning'],
        experience: 'School studies',
        livingConditions: 'Home with family',
        helpReceived: 'Teachers, family encouragement',
        suggestions: 'Keep your math strong and start exploring basic programming concepts.',
        ageRange: '14–15 years',
      },
      {
        stageName: '12th – MPC Stream',
        education: '12th with Mathematics, Physics, Chemistry',
        skills: ['Analytical thinking', 'Physics problem solving', 'Basic programming in Java/Python'],
        experience: 'Board exams and foundation programming study',
        livingConditions: 'Home / coaching',
        helpReceived: 'Coaching institutes, online tutorials',
        suggestions: 'Learn Java syntax and object-oriented concepts while preparing for boards.',
        ageRange: '16–17 years',
      },
      {
        stageName: 'Diploma / B.Tech in CSE',
        education: 'Diploma in Computer Science or B.Tech CSE / IT',
        skills: ['Java', 'Data Structures', 'Database fundamentals', 'Web services'],
        experience: 'College projects, internships',
        livingConditions: 'Hostel / PG',
        helpReceived: 'College faculty, peers, online learning platforms',
        suggestions: 'Build backend projects using Java and learn SQL thoroughly.',
        ageRange: '18–21 years',
      },
      {
        stageName: 'Junior Java Developer',
        education: 'Diploma / B.Tech completed',
        skills: ['Spring Boot', 'REST APIs', 'SQL', 'Debugging', 'Version control'],
        experience: '1–2 years in entry-level backend role',
        livingConditions: 'Rented apartment in city',
        helpReceived: 'Mentors, senior developers, code reviews',
        suggestions: 'Contribute to real backend projects and learn how to design APIs.',
        ageRange: '21–24 years',
      },
      {
        stageName: 'Senior Backend Engineer',
        education: 'B.Tech / Diploma + industry experience',
        skills: ['Microservices', 'System architecture', 'Performance tuning', 'Team leadership'],
        experience: '4–6 years building backend systems',
        livingConditions: 'Stable city living',
        helpReceived: 'Technical leads, architecture reviews',
        suggestions: 'Focus on scalable systems and backend architecture for enterprise apps.',
        ageRange: '25–28 years',
      },
    ],
    transitions: [
      {
        fromStage: '10th Standard',
        toStage: '12th – MPC Stream',
        optionsAvailable: ['Commerce', 'BiPC', 'Vocational courses'],
        reasonChosen: 'MPC keeps engineering and backend development options open.',
        mistakes: 'Delayed Java learning until college; starting earlier would help.',
        advice: 'Use 12th year to learn Java basics and problem-solving skills.',
      },
      {
        fromStage: '12th – MPC Stream',
        toStage: 'Diploma / B.Tech in CSE',
        optionsAvailable: ['Polytechnic', 'ITI', 'BCA', 'B.Sc CS'],
        reasonChosen: 'Chose a technical degree for a stronger backend engineering foundation.',
        mistakes: 'Underestimated the value of practical projects during college.',
        advice: 'Build small Java applications and backend APIs as part of your coursework.',
      },
      {
        fromStage: 'Diploma / B.Tech in CSE',
        toStage: 'Junior Java Developer',
        optionsAvailable: ['Higher studies', 'Freelancing', 'Certification courses'],
        reasonChosen: 'Secured an entry-level backend job after internship experience.',
        mistakes: 'Too much focus on theory; practical coding matters more.',
        advice: 'Practice coding regularly and focus on backend projects.',
      },
      {
        fromStage: 'Junior Java Developer',
        toStage: 'Senior Backend Engineer',
        optionsAvailable: ['Tech lead roles', 'Product engineering', 'Startup path'],
        reasonChosen: 'Gained depth in backend systems and contributed to production applications.',
        mistakes: 'Avoided learning architecture early enough.',
        advice: 'Learn microservices, deployment, and system design to grow faster.',
      },
    ],
  },

  // ─── 4. PYTHON APPLICATION DEVELOPER ───────────────────────────────────────────
  {
    title: 'Python Application Developer',
    category: 'Engineering & Tech',
    description: 'Create applications and automation tools using Python after a 12th MPC foundation.',
    submitterName: 'Neha Patel',
    submitterEmail: 'neha.patel@example.com',
    submitterGender: 'Female',
    submitterEducationHistory: '10th → 12th MPC → B.Sc IT / BCA / B.Tech IT → Python Developer',
    submitterSkills: ['Python', 'Flask/Django', 'Database design', 'Scripting', 'Debugging'],
    submitterBackground: 'Urban',
    submitterEconomicStatus: 'Middle',
    isSeeded: true,
    stages: [
      {
        stageName: '10th Standard',
        education: '10th with strong Mathematics',
        skills: ['Logical reasoning', 'Numerical ability'],
        experience: 'School education',
        livingConditions: 'Home with family',
        helpReceived: 'Teachers and parents',
        suggestions: 'Build a habit of learning small programming concepts early.',
        ageRange: '14–15 years',
      },
      {
        stageName: '12th – MPC Stream',
        education: '12th with Mathematics, Physics, Chemistry',
        skills: ['Math fundamentals', 'Problem solving', 'Intro to Python'],
        experience: 'Board exam preparation and self-study',
        livingConditions: 'Home / coaching',
        helpReceived: 'Study groups, online courses',
        suggestions: 'Start Python basics in 12th year to gain a head start.',
        ageRange: '16–17 years',
      },
      {
        stageName: 'B.Sc IT / BCA / B.Tech IT',
        education: 'Undergraduate in IT, Computer Applications or Engineering',
        skills: ['Python programming', 'Web development', 'SQL', 'Data handling'],
        experience: 'College projects, internships',
        livingConditions: 'Hostel / PG',
        helpReceived: 'Faculty mentors, online communities',
        suggestions: 'Build Python applications and learn frameworks like Flask or Django.',
        ageRange: '18–21 years',
      },
      {
        stageName: 'Junior Python Developer',
        education: 'Completed undergraduate degree',
        skills: ['Python', 'APIs', 'Automation', 'Git', 'Problem solving'],
        experience: '1–2 years building apps or automation scripts',
        livingConditions: 'Urban rented accommodation',
        helpReceived: 'Team leads, senior developers',
        suggestions: 'Work on real products and document your code portfolio.',
        ageRange: '21–24 years',
      },
      {
        stageName: 'Senior Application Developer',
        education: 'Degree + experience',
        skills: ['Software architecture', 'API design', 'Performance optimization', 'Mentoring'],
        experience: '4–6 years in Python development',
        livingConditions: 'Stable city life',
        helpReceived: 'Senior mentors and architect reviews',
        suggestions: 'Expand into data engineering, automation platforms, or web applications.',
        ageRange: '25–28 years',
      },
    ],
    transitions: [
      {
        fromStage: '10th Standard',
        toStage: '12th – MPC Stream',
        optionsAvailable: ['BiPC', 'Commerce with Math', 'Vocational studies'],
        reasonChosen: 'MPC was chosen to preserve access to technical degrees.',
        mistakes: 'Delayed hands-on coding until college.',
        advice: 'Use 12th year to explore Python and application ideas.',
      },
      {
        fromStage: '12th – MPC Stream',
        toStage: 'B.Sc IT / BCA / B.Tech IT',
        optionsAvailable: ['Diploma', 'B.Sc CS', 'B.Com IT'],
        reasonChosen: 'Chose an IT-focused degree for better Python application opportunities.',
        mistakes: 'Ignoring soft skills; communication matters in application development.',
        advice: 'Combine coding practice with writing clean, maintainable code.',
      },
      {
        fromStage: 'B.Sc IT / BCA / B.Tech IT',
        toStage: 'Junior Python Developer',
        optionsAvailable: ['Freelancing', 'Startup internship', 'Higher studies'],
        reasonChosen: 'Got a development role through portfolio projects and internships.',
        mistakes: 'Not building a strong GitHub profile early enough.',
        advice: 'Publish projects and contribute to open-source Python repositories.',
      },
      {
        fromStage: 'Junior Python Developer',
        toStage: 'Senior Application Developer',
        optionsAvailable: ['Tech lead', 'Product engineering', 'Consulting'],
        reasonChosen: 'Gained experience by working on end-to-end Python applications.',
        mistakes: 'Failed to learn system design and architecture early on.',
        advice: 'Move beyond scripts to large-scale application design and optimization.',
      },
    ],
  },

  // ─── 4. DOCTOR (MBBS → MD) ───────────────────────────────────────────────────
  {
    title: 'Doctor (MBBS → MD Specialist)',
    category: 'Medical',
    description: 'Long but rewarding path through MBBS and postgraduate medical specialization.',
    submitterName: 'Dr. Anil Verma',
    submitterEmail: 'anil.verma@example.com',
    submitterGender: 'Male',
    submitterEducationHistory: '10th → 12th BiPC → NEET Exam → MBBS → MD Specialization',
    submitterSkills: ['Empathy', 'Problem-solving', 'Attention to detail', 'Anatomy', 'Patient Care'],
    submitterBackground: 'Urban',
    submitterEconomicStatus: 'Rich',
    isSeeded: true,
    stages: [
      {
        stageName: '10th Standard',
        education: '10th with strong Science + Biology',
        skills: ['Biology basics', 'Chemistry', 'Study discipline'],
        experience: 'School',
        livingConditions: 'Home with family',
        helpReceived: 'School teachers, family',
        suggestions: 'Develop habits of reading and memorization. Biology-heavy NEET needs consistency.',
        ageRange: '14–15 years',
      },
      {
        stageName: '12th – BiPC Stream',
        education: '12th (Biology, Physics, Chemistry)',
        skills: ['Organic Chemistry', 'Human Biology', 'Physics', 'NEET Preparation'],
        experience: 'Intensive NEET coaching',
        livingConditions: 'Hostel / coaching city',
        helpReceived: 'Coaching institute, online NEET prep resources',
        suggestions: 'NEET is all about consistency across 2 years. Do not skip revisions.',
        ageRange: '16–17 years',
      },
      {
        stageName: 'MBBS (5.5 years)',
        education: 'MBBS from a government or private medical college',
        skills: ['Anatomy', 'Physiology', 'Pharmacology', 'Clinical diagnosis', 'Patient communication'],
        experience: 'Clinical rotations across departments during 3rd–5th year + 1-year internship',
        livingConditions: 'Medical college hostel',
        helpReceived: 'Professors, senior residents, clinical mentors',
        suggestions: 'Do not ignore internship rotations—practical experience is irreplaceable.',
        ageRange: '18–23 years',
      },
      {
        stageName: 'NEET-PG → MD / MS (3 years)',
        education: 'MD or MS in chosen specialization',
        skills: ['Specialization clinical skills', 'Research', 'Surgery (MS)', 'Diagnosis depth'],
        experience: 'Residency (Junior Residency in a teaching hospital)',
        livingConditions: 'Resident doctor quarters in hospital',
        helpReceived: 'Senior consultants, research supervisors',
        suggestions: 'Choose specialization aligned with your strengths and interest, not just earnings.',
        ageRange: '24–27 years',
      },
      {
        stageName: 'Specialist Doctor / Consultant',
        education: 'MD/MS + licensed practice',
        skills: ['Advanced clinical skills', 'Patient management', 'Leadership', 'Research'],
        experience: '10+ years total (MBBS + PG + practice)',
        livingConditions: 'Own home or hospital-provided accommodation',
        helpReceived: 'Professional medical associations, conferences',
        suggestions: 'Stay updated with medical journals. Consider teaching/research alongside practice.',
        ageRange: '28–35 years',
      },
    ],
    transitions: [
      {
        fromStage: '10th Standard',
        toStage: '12th – BiPC Stream',
        optionsAvailable: ['MPC for engineering', 'Commerce', 'Vocational'],
        reasonChosen: 'Clear goal of becoming a doctor; BiPC is mandatory for NEET.',
        mistakes: '',
        advice: 'Confirm your interest in medicine before committing. It is a very long and demanding path.',
      },
      {
        fromStage: '12th – BiPC Stream',
        toStage: 'MBBS (5.5 years)',
        optionsAvailable: ['B.Pharm', 'Nursing', 'B.Sc Zoology/Microbiology', 'AYUSH courses', 'Paramedical'],
        reasonChosen: 'Qualified NEET with sufficient rank for government medical college.',
        mistakes: 'Took drop year — should have applied to private college in 1st attempt while preparing.',
        advice: 'Government seats are best; if not, evaluate private college fee vs. career ROI carefully.',
      },
      {
        fromStage: 'MBBS (5.5 years)',
        toStage: 'NEET-PG → MD / MS (3 years)',
        optionsAvailable: ['General practice (GP) without PG', 'Work in rural health center', 'Abroad (USMLE)'],
        reasonChosen: 'PG specialization greatly improves scope, earnings, and satisfaction.',
        mistakes: 'Did not prepare for NEET-PG parallel to internship; lost 1 year.',
        advice: 'Start NEET-PG prep from final year MBBS itself.',
      },
      {
        fromStage: 'NEET-PG → MD / MS (3 years)',
        toStage: 'Specialist Doctor / Consultant',
        optionsAvailable: ['Super-specialization (DM/MCh)', 'Teaching (Prof)', 'Research', 'Abroad practice'],
        reasonChosen: 'Set up own clinic + hospital attachment for a balanced practice.',
        mistakes: 'Delayed setting up clinic due to financial planning gaps.',
        advice: 'Start financial planning early. Medical career starts late — plan investments accordingly.',
      },
    ],
  },

  // ─── 4. CHARTERED ACCOUNTANT (CA) ────────────────────────────────────────────
  {
    title: 'Chartered Accountant (CA)',
    category: 'Commerce & Management',
    description: 'Highly respected finance and auditing profession requiring ICAI certification after 12th Commerce.',
    submitterName: 'Meera Desai',
    submitterEmail: 'meera.desai@example.com',
    submitterGender: 'Female',
    submitterEducationHistory: '10th → 12th Commerce → CA Foundation → CA Intermediate → CA Final → Practicing CA',
    submitterSkills: ['Attention to detail', 'Numerical analysis', 'Consistency', 'Accounting', 'Taxation', 'Auditing'],
    submitterBackground: 'Urban',
    submitterEconomicStatus: 'Middle',
    isSeeded: true,
    stages: [
      {
        stageName: '10th Standard',
        education: '10th with Mathematics',
        skills: ['Mathematics', 'Logical Reasoning'],
        experience: 'School',
        livingConditions: 'Home',
        helpReceived: 'Teachers, family',
        suggestions: 'Commerce is a viable and rewarding stream. Mathematics is important for CA.',
        ageRange: '14–15 years',
      },
      {
        stageName: '12th – Commerce Stream',
        education: '12th Commerce (Accountancy, Business Studies, Economics, Math)',
        skills: ['Accountancy', 'Economics basics', 'Business concepts'],
        experience: 'Register for ICAI Foundation after 12th',
        livingConditions: 'Home',
        helpReceived: 'ICAI study materials, teachers',
        suggestions: 'Register for CA Foundation immediately after 12th results.',
        ageRange: '16–17 years',
      },
      {
        stageName: 'CA Foundation → CA Intermediate',
        education: 'CA Foundation (cleared) → CA Intermediate (pursuing)',
        skills: ['Accounting Standards', 'Taxation Law', 'Auditing', 'Cost Accounting', 'Financial Management'],
        experience: 'Self-study intensive; attempt Foundation and Intermediate exams',
        livingConditions: 'Home or CA coaching institute',
        helpReceived: 'ICAI, CA coaching classes, study groups',
        suggestions: 'Consistency is key. CA failure rate is high but persistence pays.',
        ageRange: '18–21 years',
      },
      {
        stageName: 'Articleship (3 Years)',
        education: 'CA Intermediate cleared → Articleship at CA firm',
        skills: ['Practical Auditing', 'Income Tax Filing', 'GST', 'Client Communication', 'Excel Advanced'],
        experience: '3-year mandatory articleship under a practicing CA',
        livingConditions: 'Home or PG near CA firm',
        helpReceived: 'Principal CA, firm seniors, ICAI resources',
        suggestions: 'Choose an articleship firm that exposes you to diverse clients and industries.',
        ageRange: '20–23 years',
      },
      {
        stageName: 'CA Final → Practicing CA / Industry CFO',
        education: 'CA Final cleared → ICAI Member',
        skills: ['Corporate Law', 'Strategic Financial Management', 'Advanced Auditing', 'Advisory'],
        experience: 'Post-qualification jobs or own practice',
        livingConditions: 'Own setup or corporate environment',
        helpReceived: 'Professional networks, ICAI continuing education',
        suggestions: 'CA opens doors to Big 4, corporate finance, own practice, and international opportunities.',
        ageRange: '24–28 years',
      },
    ],
    transitions: [
      {
        fromStage: '10th Standard',
        toStage: '12th – Commerce Stream',
        optionsAvailable: ['MPC', 'BiPC', 'Arts'],
        reasonChosen: 'Interest in finance and business led to Commerce choice.',
        mistakes: '',
        advice: 'CA is possible from any stream but Commerce makes the journey smoother.',
      },
      {
        fromStage: '12th – Commerce Stream',
        toStage: 'CA Foundation → CA Intermediate',
        optionsAvailable: ['B.Com (then pursue CA)', 'BBA', 'MBA directly', 'Banking exams'],
        reasonChosen: 'Direct CA route is faster and more focused.',
        mistakes: 'Did not take Foundation seriously — should prepare months before the exam.',
        advice: 'CA Foundation is the gateway; do not underestimate it.',
      },
      {
        fromStage: 'CA Foundation → CA Intermediate',
        toStage: 'Articleship (3 Years)',
        optionsAvailable: ['Stop at Intermediate level (semi-qualified)', 'BBA alongside'],
        reasonChosen: 'Articleship is mandatory and provides real-world exposure.',
        mistakes: 'Rushed articleship selection; should evaluate the firm type carefully.',
        advice: 'Big firm vs. small firm both have pros/cons. Big firm = brand; small firm = more work variety.',
      },
      {
        fromStage: 'Articleship (3 Years)',
        toStage: 'CA Final → Practicing CA / Industry CFO',
        optionsAvailable: ['CMA (Cost Accounting)', 'CS (Company Secretary)', 'MBA Finance'],
        reasonChosen: 'Cleared CA Final; joined Big 4 audit firm initially.',
        mistakes: 'Delayed CA Final attempts due to articleship workload burden.',
        advice: 'Plan CA Final studies alongside articleship systematically. Do not delay.',
      },
    ],
  },

  // ─── 5. GRAPHIC DESIGNER ─────────────────────────────────────────────────────
  {
    title: 'Graphic Designer',
    category: 'Creative Fields',
    description: 'Visual communication professional working across branding, digital media, and print.',
    submitterName: 'Arjun Singh',
    submitterEmail: 'arjun.singh@example.com',
    submitterGender: 'Male',
    submitterEducationHistory: '10th → 12th → Diploma in Graphic Design → BFA',
    submitterSkills: ['Creativity', 'Visual thinking', 'Attention to aesthetics', 'Photoshop', 'Typography', 'Design'],
    submitterBackground: 'Semi-Urban',
    submitterEconomicStatus: 'Middle',
    isSeeded: true,
    stages: [
      {
        stageName: '10th Standard',
        education: '10th – any stream',
        skills: ['Drawing', 'Creativity', 'Color Sense', 'Basic Computer'],
        experience: 'School art classes, personal sketching',
        livingConditions: 'Home',
        helpReceived: 'Art teachers, family encouragement',
        suggestions: 'Build a personal sketchbook. Start studying great logos and visual designs around you.',
        ageRange: '14–16 years',
      },
      {
        stageName: '12th & Short Courses in Design',
        education: '12th (any stream) + online/offline design courses',
        skills: ['Photoshop basics', 'Canva', 'Typography', 'Logo design basics'],
        experience: 'Freelance small projects, social media assets for local businesses',
        livingConditions: 'Home',
        helpReceived: 'YouTube tutorials, Skillshare, online communities',
        suggestions: 'Start freelancing early — even small projects build your portfolio.',
        ageRange: '17–18 years',
      },
      {
        stageName: 'B.Des / BFA / Diploma in Graphic Design',
        education: 'Undergraduate design degree or diploma (3–4 years)',
        skills: ['Adobe Creative Suite', 'Brand Identity', 'UI/UX basics', 'Motion Graphics', 'Print Design'],
        experience: 'Internships at design studios, freelance projects, competitions',
        livingConditions: 'Hostel or home',
        helpReceived: 'Design faculty, studio mentors, Behance community',
        suggestions: 'Build a strong Behance/Dribbble portfolio during college. Quality over quantity.',
        ageRange: '18–22 years',
      },
      {
        stageName: 'Junior Graphic Designer',
        education: 'B.Des / BFA + 0–2 years experience',
        skills: ['Client communication', 'Mockups', 'Brand guidelines', 'Presentation', 'Feedback incorporation'],
        experience: 'Agency or in-house designer',
        livingConditions: 'PG/rented room near workplace',
        helpReceived: 'Senior designers, art directors',
        suggestions: 'Learn to take feedback constructively. Design is collaborative.',
        ageRange: '22–25 years',
      },
      {
        stageName: 'Senior Designer / Creative Director / Freelancer',
        education: 'Experience + specialized skills',
        skills: ['Art Direction', 'Team Leadership', 'Client Management', 'Motion Graphics', 'Strategy'],
        experience: '5+ years, portfolio of 50+ quality projects',
        livingConditions: 'Own space or remote work setup',
        helpReceived: 'Client network, design community',
        suggestions: 'Freelancing offers freedom but demands self-discipline. Build a niche early.',
        ageRange: '27–35 years',
      },
    ],
    transitions: [
      {
        fromStage: '10th Standard',
        toStage: '12th & Short Courses in Design',
        optionsAvailable: ['Join Arts stream', 'Any stream + self-study design', 'Commerce / Science'],
        reasonChosen: 'Design does not strictly require a fixed 12th stream; passion matters more.',
        mistakes: '',
        advice: 'Start building your design portfolio from 10th itself using free tools like Canva.',
      },
      {
        fromStage: '12th & Short Courses in Design',
        toStage: 'B.Des / BFA / Diploma in Graphic Design',
        optionsAvailable: ['Direct freelancing', 'Online certifications only', 'Arts college'],
        reasonChosen: 'Formal degree adds structure, mentorship, and credential value.',
        mistakes: 'Applied to NID/NIFT without portfolio. Prepare portfolio 6 months before exam.',
        advice: 'For NID/NIFT, design portfolio and aptitude test prep starts early.',
      },
      {
        fromStage: 'B.Des / BFA / Diploma in Graphic Design',
        toStage: 'Junior Graphic Designer',
        optionsAvailable: ['Full-time freelancing', 'Start own studio', 'UI/UX specialization'],
        reasonChosen: 'Joined an agency to learn the professional workflow and client handling.',
        mistakes: 'Took first job offer without evaluating portfolio fit; cultural match matters.',
        advice: 'Join a company where your creative sensities are valued, not just speed of output.',
      },
      {
        fromStage: 'Junior Graphic Designer',
        toStage: 'Senior Designer / Creative Director / Freelancer',
        optionsAvailable: ['Pivoting to UX/UI', 'Motion design', 'Brand strategy', 'Teaching design'],
        reasonChosen: 'Built expertise in brand identity and grew to creative direction.',
        mistakes: 'Did not raise rates early enough as a freelancer; research market rates.',
        advice: 'Build your personal brand (social media presence) — it brings clients to you.',
      },
    ],
  },

  // ─── 6. UPSC (IAS OFFICER) ───────────────────────────────────────────────────
  {
    title: 'IAS Officer (UPSC Civil Services)',
    category: 'Government Jobs',
    description: 'India\'s most prestigious civil service role, requiring clearing UPSC CSE across three stages.',
    submitterName: 'Vikram Patel',
    submitterEmail: 'vikram.patel@example.com',
    submitterGender: 'Male',
    submitterEducationHistory: '10th → 12th Arts → BA History → UPSC Preparation → IAS',
    submitterSkills: ['Reading and writing', 'Leadership', 'General awareness', 'Current Affairs', 'Government', 'Policy'],
    submitterBackground: 'Rural',
    submitterEconomicStatus: 'Poor',
    isSeeded: true,
    stages: [
      {
        stageName: '10th Standard',
        education: '10th – any board',
        skills: ['Reading habits', 'Current affairs awareness', 'Writing basics'],
        experience: 'School',
        livingConditions: 'Home',
        helpReceived: 'Teachers, local library',
        suggestions: 'Develop reading habit early. Start reading newspapers regularly.',
        ageRange: '14–15 years',
      },
      {
        stageName: '12th – Any Stream',
        education: '12th (Science / Commerce / Arts – any)',
        skills: ['Writing skills', 'History/Geography/Civics', 'Analytical thinking'],
        experience: 'School studies',
        livingConditions: 'Home',
        helpReceived: 'NCERT books, school teachers',
        suggestions: 'Read NCERT books thoroughly — they form the backbone of UPSC Prelims/Mains.',
        ageRange: '16–17 years',
      },
      {
        stageName: 'Undergraduate Degree',
        education: 'Any UG degree (minimum eligibility for UPSC)',
        skills: ['Optional subject depth', 'Essay writing', 'Current affairs', 'Critical analysis'],
        experience: 'Parallel UPSC preparation alongside degree',
        livingConditions: 'Home or hostel',
        helpReceived: 'Coaching centers, online resources, study groups',
        suggestions: 'Choose optional subject wisely — it decides 500/1750 marks. Align with interest.',
        ageRange: '18–21 years',
      },
      {
        stageName: 'UPSC Preparation (1–4 years)',
        education: 'UG completed; focused UPSC prep',
        skills: ['UPSC Prelims strategy', 'Answer writing', 'Interview preparation', 'Newspaper reading'],
        experience: 'Mock tests, answer writing practice, coaching (optional)',
        livingConditions: 'Delhi / coaching city or home',
        helpReceived: 'IAS coaching, previous year toppers\' resources, ForumIAS, Insights IAS',
        suggestions: 'Consistency over 1–4 years wins. Do not compare with peers — focus on your plan.',
        ageRange: '22–26 years',
      },
      {
        stageName: 'IAS/IPS/IFS Officer',
        education: 'UPSC CSE cleared → Lal Bahadur Shastri National Academy training',
        skills: ['Administration', 'Policy Making', 'Public Service', 'Crisis Management', 'Leadership'],
        experience: 'District-level posting initially; grows to state/national level',
        livingConditions: 'Government bungalow with staff',
        helpReceived: 'Batch seniors, mentors in the service',
        suggestions: 'Stay grounded in public service values. Integrity is your biggest asset.',
        ageRange: '26–35 years',
      },
    ],
    transitions: [
      {
        fromStage: '10th Standard',
        toStage: '12th – Any Stream',
        optionsAvailable: ['Any stream — Science, Commerce, Arts'],
        reasonChosen: 'Any 12th stream is eligible for UPSC. Humanities helps but is not mandatory.',
        mistakes: '',
        advice: 'Arts/Humanities stream aligns closely with UPSC syllabus. But any stream can succeed.',
      },
      {
        fromStage: '12th – Any Stream',
        toStage: 'Undergraduate Degree',
        optionsAvailable: ['BA History/Political Science', 'BTech', 'BCom', 'BSc'],
        reasonChosen: 'BA gives time to study UPSC alongside; technical degrees give alternative backup.',
        mistakes: 'Joining a tough technical course that leaves no time for UPSC preparation.',
        advice: 'Whatever UG you choose, start reading newspapers and NCERT from 1st year.',
      },
      {
        fromStage: 'Undergraduate Degree',
        toStage: 'UPSC Preparation (1–4 years)',
        optionsAvailable: ['Job then UPSC', 'State PCS exam', 'MBA', 'Postgraduate degree'],
        reasonChosen: 'Dedicated full-time UPSC preparation after UG.',
        mistakes: 'Delayed preparation waiting for "readiness" — start early.',
        advice: 'Have a financial backup plan. UPSC takes 2–4 years of dedicated effort typically.',
      },
      {
        fromStage: 'UPSC Preparation (1–4 years)',
        toStage: 'IAS/IPS/IFS Officer',
        optionsAvailable: ['State PSC', 'SSC CGL (Central services)', 'Reattempting UPSC'],
        reasonChosen: 'Cleared UPSC in 3rd attempt with All India Rank 47.',
        mistakes: 'Over-relying on coaching; self-study and answer writing practice is more important.',
        advice: 'Clear Prelims with speed and accuracy; Mains with quality answer writing; Interview with authenticity.',
      },
    ],
  },

  // ─── 7. NURSE ────────────────────────────────────────────────────────────────
  {
    title: 'Registered Nurse',
    category: 'Medical',
    description: 'Healthcare professional providing patient care, medication management, and clinical support.',
    submitterName: 'Anjali Gupta',
    submitterEmail: 'anjali.gupta@example.com',
    submitterGender: 'Female',
    submitterEducationHistory: '10th → 12th BiPC → B.Sc Nursing → Staff Nurse',
    submitterSkills: ['Empathy', 'Patient care', 'Teamwork', 'Medical knowledge', 'Clinical skills'],
    submitterBackground: 'Semi-Urban',
    submitterEconomicStatus: 'Middle',
    isSeeded: true,
    stages: [
      { stageName: '10th Standard', education: '10th with Science', skills: ['Biology', 'Basic Chemistry'], experience: 'School', livingConditions: 'Home', helpReceived: 'Teachers', suggestions: 'Biology and chemistry are key for nursing entrance exams.', ageRange: '14–15 years' },
      { stageName: '12th – BiPC', education: '12th Biology, Physics, Chemistry', skills: ['Human Biology', 'Chemistry', 'First Aid basics'], experience: 'School, volunteer at local hospital', livingConditions: 'Home or coaching', helpReceived: 'Teachers, NEET coaching', suggestions: 'Volunteer at local health centers to get a feel for patient care.', ageRange: '16–17 years' },
      { stageName: 'B.Sc Nursing or GNM (3 years)', education: 'Bachelor of Science in Nursing (4 years) or GNM Diploma (3 years)', skills: ['Clinical nursing', 'Patient assessment', 'Medication administration', 'OT techniques', 'Emergency care'], experience: 'Clinical rotations in hospitals across departments', livingConditions: 'College hostel', helpReceived: 'Clinical supervisors, senior nurses', suggestions: 'Clinical rotations are gold — absorb as much as you can in diverse wards.', ageRange: '17–21 years' },
      { stageName: 'Staff Nurse', education: 'B.Sc/GNM + State Nursing Council registration', skills: ['ICU nursing', 'Ventilator care', 'Team coordination', 'Documentation'], experience: '1–5 years in government/private hospitals', livingConditions: 'Hospital quarters or nearby PG', helpReceived: 'Senior staff, doctors, charge nurses', suggestions: 'Government hospital jobs provide job security. Private hospitals offer higher pay.', ageRange: '21–26 years' },
      { stageName: 'Senior Nurse / Nursing Officer / M.Sc Nursing', education: 'M.Sc Nursing or senior clinical role', skills: ['Leadership', 'Training junior nurses', 'Administration', 'Research'], experience: '5–10 years', livingConditions: 'Own home', helpReceived: 'Professional associations, INC', suggestions: 'M.Sc Nursing opens teaching and managerial roles. Consider it after 5 years of experience.', ageRange: '26–32 years' },
    ],
    transitions: [
      { fromStage: '10th Standard', toStage: '12th – BiPC', optionsAvailable: ['MPC', 'Commerce', 'Arts'], reasonChosen: 'BiPC is mandatory for nursing entrance.', mistakes: '', advice: 'Biology is non-negotiable for a healthcare career.' },
      { fromStage: '12th – BiPC', toStage: 'B.Sc Nursing or GNM (3 years)', optionsAvailable: ['MBBS', 'B.Pharm', 'Paramedical', 'ANM'], reasonChosen: 'B.Sc Nursing offers wider scope than ANM. GNM is faster route.', mistakes: 'Choosing private college without verifying nursing council affiliation.', advice: 'Verify nursing college is INC approved before admission.' },
      { fromStage: 'B.Sc Nursing or GNM (3 years)', toStage: 'Staff Nurse', optionsAvailable: ['Abroad nursing (UK/USA/Gulf)', 'Government exam (AIIMS, NHM)', 'Private hospitals'], reasonChosen: 'Government job provides stability and pension.', mistakes: 'Not preparing for government nursing exams early enough.', advice: 'Start preparing for AIIMS nursing officer, NHM, ESIC exams from final year.' },
      { fromStage: 'Staff Nurse', toStage: 'Senior Nurse / Nursing Officer / M.Sc Nursing', optionsAvailable: ['Abroad (UK OSCE, USA NCLEX)', 'Teaching role', 'Hospital Admin'], reasonChosen: 'M.Sc opened teaching at a nursing college.', mistakes: '', advice: 'NCLEX (USA) is very lucrative; pursue if willing to relocate abroad.' },
    ],
  },

  // ─── 8. ELECTRICIAN / ELECTRICAL TECHNICIAN ──────────────────────────────────
  {
    title: 'Electrician / Electrical Technician',
    category: 'Skilled Trades',
    description: 'Skilled trade professional handling electrical wiring, maintenance, and industrial systems.',
    submitterName: 'Ramesh Kumar',
    submitterEmail: 'ramesh.kumar@example.com',
    submitterGender: 'Male',
    submitterEducationHistory: '10th → ITI Electrician → 3 years apprenticeship → Licensed Electrician',
    submitterSkills: ['Problem-solving', 'Technical aptitude', 'Safety awareness', 'Electrical wiring', 'Maintenance'],
    submitterBackground: 'Rural',
    submitterEconomicStatus: 'Poor',
    isSeeded: true,
    stages: [
      { stageName: '10th Standard', education: '10th (pass in Math and Science)', skills: ['Basic Electricity concepts', 'Mathematics', 'Physical work stamina'], experience: 'School', livingConditions: 'Home in rural/semi-urban area', helpReceived: 'School and family', suggestions: 'Develop hands-on curiosity — open broken appliances, understand how things work.', ageRange: '14–16 years' },
      { stageName: 'ITI – Electrician Trade (2 years)', education: 'ITI Certificate in Electrician Trade (NCVT/SCVT)', skills: ['Basic wiring', 'Circuit diagrams', 'Safety norms', 'Panel board installation', 'Motor wiring'], experience: 'Workshop practice in ITI for domestic and industrial electrical work', livingConditions: 'Home or ITI hostel', helpReceived: 'ITI instructors, industry mentors during on-job training', suggestions: 'Attend every practical session. Theory without practice is useless in this trade.', ageRange: '16–18 years' },
      { stageName: 'Apprenticeship / On-Job Training (1–2 years)', education: 'ITI + Apprenticeship (under Apprenticeship Act)', skills: ['Industrial panel wiring', 'Troubleshooting', 'Energy meters', 'Solar panel basics'], experience: '1–2 years in factory, construction site, or government electrical dept.', livingConditions: 'Company quarters or local room', helpReceived: 'Supervisor electricians, company mentors', suggestions: 'Learn to read electrical drawings and single-line diagrams. These get you better jobs.', ageRange: '18–20 years' },
      { stageName: 'Licensed Electrician / Supervisor', education: 'ITI + Electrical License from State Electrical Inspectorate', skills: ['Project supervision', 'Safety audit', 'Power plant systems', 'HT/LT installations'], experience: '3–7 years in construction, manufacturing, or power sector', livingConditions: 'Own home or rented', helpReceived: 'Contractor network, licensing authority', suggestions: 'Get your electrical license — it greatly increases your earning and credibility.', ageRange: '21–28 years' },
      { stageName: 'Electrical Contractor / Senior Technician', education: 'License + Diploma in Electrical Engineering (lateral entry optional)', skills: ['Tender management', 'Client handling', 'Team supervision', 'Contract bidding'], experience: '8–15 years, own business or senior role', livingConditions: 'Own home, own vehicle', helpReceived: 'Government contractor empanelment, bank loans for tools', suggestions: 'Register as a contractor and bid for government electrical projects. Very lucrative.', ageRange: '28–40 years' },
    ],
    transitions: [
      { fromStage: '10th Standard', toStage: 'ITI – Electrician Trade (2 years)', optionsAvailable: ['12th then diploma', '12th then degree', 'Direct work as helper'], reasonChosen: 'ITI after 10th is fastest route to a skilled trade and income.', mistakes: 'Did not research which ITI has better workshop equipment.', advice: 'Visit ITI before admission; check tools/machines available.' },
      { fromStage: 'ITI – Electrician Trade (2 years)', toStage: 'Apprenticeship / On-Job Training (1–2 years)', optionsAvailable: ['Direct helper job', 'Diploma via LEET', 'Government PSU exam'], reasonChosen: 'Apprenticeship gives structured exposure in an actual factory setting.', mistakes: 'Skipped apprenticeship and started work directly; lost structured learning.', advice: 'Apprenticeship stipend is small but knowledge gained is priceless.' },
      { fromStage: 'Apprenticeship / On-Job Training (1–2 years)', toStage: 'Licensed Electrician / Supervisor', optionsAvailable: ['Remain as technician', 'Study for diploma laterally', 'Gulf electrical job'], reasonChosen: 'Got electrical wireman license; expanded scope of work.',  mistakes: '', advice: 'Solar and EV charging are the future — get certified in these during this stage.' },
      { fromStage: 'Licensed Electrician / Supervisor', toStage: 'Electrical Contractor / Senior Technician', optionsAvailable: ['Government department job (DISCOMS)', 'Private plant maintenance', 'Own contracting business'], reasonChosen: 'Started own contracting business after building 10 years of client trust.', mistakes: 'Undercharged in early contracting days. Know market rates.', advice: 'Join electrical contractor associations — they provide training, tenders, and networking.' },
    ],
  },

  // ─── 9. FARMER → AGRIBUSINESS ENTREPRENEUR ────────────────────────────────────
  {
    title: 'Farmer → Agribusiness Entrepreneur',
    category: 'Rural / Non-traditional',
    description: 'Transforming traditional farming into a productive agribusiness using modern techniques and market linkage.',
    submitterName: 'Mohan Singh',
    submitterEmail: 'mohan.singh@example.com',
    submitterGender: 'Male',
    submitterEducationHistory: '10th → 12th → BSc Agriculture → FPO Formation → Export Business',
    submitterSkills: ['Business acumen', 'Leadership', 'Technical knowledge', 'Farming', 'Market Linkage'],
    submitterBackground: 'Rural',
    submitterEconomicStatus: 'Poor',
    isSeeded: true,
    stages: [
      { stageName: 'Primary Schooling & Farm Work', education: 'Up to 10th schooling alongside farming activities', skills: ['Traditional farming', 'Crop knowledge', 'Livestock care', 'Basic math for trade'], experience: 'Worked on family farm from childhood', livingConditions: 'Rural village home, agricultural land', helpReceived: 'Family, village elders, panchayat', suggestions: 'Observe how experienced farmers make decisions. Learn to read soil and weather.', ageRange: '10–16 years' },
      { stageName: '12th or BSc Agriculture', education: '12th (PCB/PCM) or BSc Agriculture from State Agricultural University', skills: ['Scientific farming', 'Fertilizer management', 'Irrigation techniques', 'Crop diseases', 'Horticulture'], experience: 'Farm internships, Krishi Vigyan Kendra training', livingConditions: 'Home or agricultural college hostel', helpReceived: 'ICAR, KVK, college professors, ATMA', suggestions: 'BSc Agriculture is highly recommended. Government schemes heavily favor educated farmers.', ageRange: '17–21 years' },
      { stageName: 'Modern Farming Adoption', education: 'BSc Agriculture + skill training (drip irrigation, greenhouse, organic farming)', skills: ['Drip irrigation', 'Hydroponics', 'Market Linkage', 'FPO participation', 'Government scheme applications'], experience: 'Implemented modern techniques on family land; 2x yield improvement', livingConditions: 'Village with improved infrastructure', helpReceived: 'KVK trainers, NABARD, state agriculture department, NGOs', suggestions: 'Apply for PM-KISAN, soil health card, and crop insurance immediately. Do not skip these.', ageRange: '21–26 years' },
      { stageName: 'Agribusiness / FPO (Farmer Producer Organization)', education: 'Skill certifications + business knowledge', skills: ['Supply chain management', 'Value addition (processing)', 'Export documentation', 'Team leadership', 'Accounting'], experience: 'Started or joined an FPO; aggregating produce from 30+ farmers', livingConditions: 'Improved village home', helpReceived: 'NABARD, SFAC, agriculture startup mentors', suggestions: 'FPOs unlock collective bargaining power and bulk sales. Register your FPO early.', ageRange: '26–32 years' },
      { stageName: 'Agro-entrepreneur / Exporter / Brand Owner', education: 'Business upskilling (MANAGE, ICAR programs, MSME training)', skills: ['Brand building', 'E-commerce (Meesho/Amazon Agri)', 'Export documentation', 'Food safety certifications'], experience: 'Exporting processed products or selling under own brand', livingConditions: 'Improved property, warehouse', helpReceived: 'APEDA, FIEO, state export promotional council', suggestions: 'Direct-to-consumer (D2C) organic brands are exploding. Build your brand story.', ageRange: '32–45 years' },
    ],
    transitions: [
      { fromStage: 'Primary Schooling & Farm Work', toStage: '12th or BSc Agriculture', optionsAvailable: ['Continue traditional farming', 'Migrate to city for work', 'ITI trade', 'BSc Agriculture'], reasonChosen: 'BSc Agriculture to bring scientific knowledge to the farm and access government schemes.', mistakes: 'Almost dropped out due to financial constraints; used state scholarship to continue.', advice: 'Scholarships for rural SC/ST/OBC students in agriculture are widely available. Apply for all.' },
      { fromStage: '12th or BSc Agriculture', toStage: 'Modern Farming Adoption', optionsAvailable: ['Job in agri-input company', 'Government Agri officer exam', 'Research/teaching'], reasonChosen: 'Returned to farming to implement knowledge on own land first.', mistakes: 'Tried too many new techniques at once; should test on small plots first.', advice: 'Pilot new techniques on 10–15% of your land before full-scale change.' },
      { fromStage: 'Modern Farming Adoption', toStage: 'Agribusiness / FPO (Farmer Producer Organization)', optionsAvailable: ['Continue individual farming', 'Contract farming for a company', 'Cold storage/logistics business'], reasonChosen: 'Collective FPO model increased negotiation power and access to credit.', mistakes: 'Avoided FPO initially due to trust issues. Took too long to join.', advice: 'A well-run FPO changes everything. Research successful FPOs in your district.' },
      { fromStage: 'Agribusiness / FPO (Farmer Producer Organization)', toStage: 'Agro-entrepreneur / Exporter / Brand Owner', optionsAvailable: ['Expand FPO', 'Agri-tech startup', 'Processing unit only', 'Grain/commodity trading'], reasonChosen: 'Built organic product brand; selling on e-commerce with 300% higher margin vs raw produce.', mistakes: 'Underestimated the importance of FSSAI certification; delayed launch.', advice: 'Value addition (processing, packaging, branding) is where profit truly lies in agri.' },
    ],
  },

  // ─── 10. CONTENT CREATOR / DIGITAL MARKETER ──────────────────────────────────
  {
    title: 'Content Creator / Digital Marketer',
    category: 'Creative Fields',
    description: 'Build a personal brand or career in digital marketing through content creation on social media and brand collaborations.',
    submitterName: 'Sneha Roy',
    submitterEmail: 'sneha.roy@example.com',
    submitterGender: 'Female',
    submitterEducationHistory: '10th → 12th → BA Marketing → Digital Marketing Certification',
    submitterSkills: ['Creativity', 'Communication', 'Tech-savviness', 'Content creation', 'Social Media', 'Analytics'],
    submitterBackground: 'Urban',
    submitterEconomicStatus: 'Middle',
    isSeeded: true,
    stages: [
      { stageName: '10th / 12th + Self Discovery', education: '10th or 12th – any stream', skills: ['Smartphone photography/video', 'Writing', 'Social media usage', 'Storytelling'], experience: 'Personal social media account experiments, school projects', livingConditions: 'Home', helpReceived: 'Online communities, YouTube tutorials', suggestions: 'Start a YouTube channel or Instagram page NOW. Fail early and learn fast.', ageRange: '15–18 years' },
      { stageName: 'Undergraduate Degree + Digital Upskilling', education: 'BA/BCom/BMM or any UG + Google Digital Marketing, HubSpot, Meta Blueprint certifications', skills: ['Content writing', 'Graphic design basics', 'Video editing (CapCut/Premiere)', 'SEO', 'Email marketing', 'Analytics'], experience: 'Freelance content for small businesses, internships at agencies, YouTube monetization', livingConditions: 'Home or hostel', helpReceived: 'Online courses, YouTube tutorials, agency internship mentors', suggestions: 'Monetize your skill by offering services to local businesses while studying.', ageRange: '18–22 years' },
      { stageName: 'Digital Marketing Executive / Content Creator', education: 'UG + certifications + 1–2 years experience', skills: ['Paid ads (Meta/Google)', 'Influencer outreach', 'Content calendar', 'Analytics reporting', 'Brand storytelling'], experience: 'Full-time role at agency or brand, growing own channel simultaneously', livingConditions: 'PG or own room, work from home setup', helpReceived: 'Agency mentors, creator communities, brand managers', suggestions: 'Dual track: agency job + personal brand. The personal brand becomes your leverage.', ageRange: '22–25 years' },
      { stageName: 'Senior Digital Marketer / Full-time Creator', education: 'Experience-based + udemy/coursera advanced courses', skills: ['Brand strategy', 'Performance marketing', 'Influencer deal negotiation', 'Community building', 'Monetization strategies'], experience: '100K+ followers on at least one platform, brand deals, 3–5 years experience', livingConditions: 'Own setup, home studio', helpReceived: 'Manager/MCN, creator peer network, brand deal agencies', suggestions: 'Diversify income: brand deals + courses + merchandise + consulting. Never single-stream.', ageRange: '25–30 years' },
    ],
    transitions: [
      { fromStage: '10th / 12th + Self Discovery', toStage: 'Undergraduate Degree + Digital Upskilling', optionsAvailable: ['Skip UG (full-time creator)', 'Journalism/Mass Communication degree', 'MBA Marketing later'], reasonChosen: 'UG provides a safety net while skills are built. Mass comm/BMM degrees are directly relevant.', mistakes: 'Wasted first year of college without building any digital skills.', advice: 'Do not wait for "right time" to start creating. Start messy. Improve with every post.' },
      { fromStage: 'Undergraduate Degree + Digital Upskilling', toStage: 'Digital Marketing Executive / Content Creator', optionsAvailable: ['Full-time freelancing', 'In-house brand team', 'Agency', 'YouTube full time'], reasonChosen: 'Agency job gives portfolio diversity and teaches multiple verticals fast.', mistakes: 'Underpriced freelance services out of insecurity early on.', advice: 'Always show ROI (reach, engagement, sales) of your content work when applying for jobs.' },
      { fromStage: 'Digital Marketing Executive / Content Creator', toStage: 'Senior Digital Marketer / Full-time Creator', optionsAvailable: ['Product manager pivot', 'EdTech (teach digital marketing)', 'Start own agency', 'Brand side job'], reasonChosen: 'Grew channel to 500K subscribers, quit job to go full-time creator.', mistakes: 'Delayed monetization of channel — should have started from 10K followers.', advice: 'Join creator economy programs early: YouTube Partner, Meta Creator Studio, Patreon.' },
    ],
  },

  // ─── 11. ZOOLOGIST / WILDLIFE BIOLOGIST ────────────────────────────────────────
  {
    title: 'Zoologist / Wildlife Biologist',
    category: 'Medical',
    description: 'Study animal behavior, ecology, and conservation through field research and laboratory work.',
    submitterName: 'Dr. Priya Singh',
    submitterEmail: 'priya.singh@example.com',
    submitterGender: 'Female',
    submitterEducationHistory: '10th → 12th BiPC → BSc Zoology → MSc Zoology → PhD Wildlife Biology',
    submitterSkills: ['Animal observation', 'Field research', 'Data analysis', 'Ecology knowledge', 'Conservation planning', 'Scientific writing'],
    submitterBackground: 'Semi-Urban',
    submitterEconomicStatus: 'Middle',
    isSeeded: true,
    stages: [
      { stageName: '10th Standard', education: '10th with strong Biology marks', skills: ['Biology basics', 'Animal curiosity', 'Nature observation'], experience: 'School biology projects, nature walks', livingConditions: 'Home', helpReceived: 'Biology teachers, local libraries', suggestions: 'Develop interest in animals through books and documentaries. Join nature clubs.', ageRange: '14–15 years' },
      { stageName: '12th – BiPC Stream', education: '12th Biology, Physics, Chemistry', skills: ['Human Biology', 'Ecology basics', 'Animal Physiology', 'NEET preparation'], experience: 'Biology practicals, science exhibitions', livingConditions: 'Home or coaching', helpReceived: 'Biology teachers, coaching institutes', suggestions: 'Focus on Biology and Chemistry. Consider NEET if interested in veterinary medicine.', ageRange: '16–17 years' },
      { stageName: 'BSc Zoology / Wildlife Biology', education: 'Bachelor of Science in Zoology (3 years)', skills: ['Animal taxonomy', 'Ecology', 'Animal behavior', 'Microscopy', 'Field sampling', 'Data recording'], experience: 'Lab work, field trips to wildlife sanctuaries, research projects', livingConditions: 'College hostel', helpReceived: 'Zoology professors, lab assistants, field guides', suggestions: 'Participate in all field trips. Learn to identify local fauna and flora.', ageRange: '18–21 years' },
      { stageName: 'MSc Zoology / Wildlife Science', education: 'Master of Science in Zoology or Wildlife Biology (2 years)', skills: ['Advanced ecology', 'Conservation biology', 'Research methodology', 'Statistical analysis', 'GIS mapping'], experience: 'Thesis research, wildlife surveys, internships at NGOs', livingConditions: 'Hostel or research accommodation', helpReceived: 'Research supervisors, wildlife experts, NGOs', suggestions: 'Choose a specialization (marine biology, ornithology, herpetology). Build publication record.', ageRange: '21–23 years' },
      { stageName: 'PhD / Research Zoologist', education: 'PhD in Zoology/Wildlife Biology (3–5 years)', skills: ['Advanced research', 'Grant writing', 'Scientific publishing', 'Project management', 'Policy advocacy'], experience: 'Original research, publications, conference presentations', livingConditions: 'University/research institute accommodation', helpReceived: 'PhD guide, research collaborators, funding agencies', suggestions: 'Publish in reputed journals. Network with international researchers.', ageRange: '23–28 years' },
      { stageName: 'Wildlife Biologist / Conservation Scientist', education: 'PhD + postdoctoral experience', skills: ['Conservation planning', 'Environmental impact assessment', 'Policy development', 'Public outreach', 'Fundraising'], experience: 'Government wildlife department, NGOs, research institutions', livingConditions: 'Field stations or urban offices', helpReceived: 'Government agencies, international organizations, professional networks', suggestions: 'Balance field work with administrative responsibilities. Stay updated with conservation policies.', ageRange: '28–35 years' },
    ],
    transitions: [
      { fromStage: '10th Standard', toStage: '12th – BiPC Stream', optionsAvailable: ['MPC for other sciences', 'Commerce', 'Arts'], reasonChosen: 'Biology is the foundation for zoology and wildlife careers.', mistakes: '', advice: 'Read books by famous naturalists like Jane Goodall and David Attenborough.' },
      { fromStage: '12th – BiPC Stream', toStage: 'BSc Zoology / Wildlife Biology', optionsAvailable: ['BSc Botany', 'BSc Microbiology', 'MBBS', 'Veterinary Science'], reasonChosen: 'Zoology degree provides comprehensive knowledge of animal kingdom.', mistakes: 'Chose college based on reputation rather than faculty expertise in wildlife.', advice: 'Visit colleges to check their zoology labs and field trip programs.' },
      { fromStage: 'BSc Zoology / Wildlife Biology', toStage: 'MSc Zoology / Wildlife Science', optionsAvailable: ['Direct job in zoos/aquariums', 'Wildlife photography', 'Teaching'], reasonChosen: 'Masters degree opens research and higher-level conservation jobs.', mistakes: 'Did not gain enough field experience during BSc.', advice: 'Volunteer with wildlife NGOs during vacations. Build practical experience.' },
      { fromStage: 'MSc Zoology / Wildlife Science', toStage: 'PhD / Research Zoologist', optionsAvailable: ['Industry jobs in pharma/ biotech', 'Environmental consulting', 'Wildlife tourism'], reasonChosen: 'PhD enables original research and academic positions.', mistakes: 'Chose topic without considering funding availability.', advice: 'Apply for research fellowships early. Network with potential PhD guides.' },
      { fromStage: 'PhD / Research Zoologist', toStage: 'Wildlife Biologist / Conservation Scientist', optionsAvailable: ['Academic positions', 'International organizations', 'Private sector consulting'], reasonChosen: 'Government job provides stability and impact on national conservation policies.', mistakes: 'Underestimated the bureaucratic aspects of government jobs.', advice: 'Prepare for UPSC IFS alongside PhD if interested in government wildlife roles.' },
    ],
  },

  // ─── 12. MICROBIOLOGIST ───────────────────────────────────────────────────────
  {
    title: 'Microbiologist',
    category: 'Medical',
    description: 'Study microorganisms and their applications in healthcare, food, environment, and research.',
    submitterName: 'Dr. Rajesh Sharma',
    submitterEmail: 'rajesh.sharma@example.com',
    submitterGender: 'Male',
    submitterEducationHistory: '10th → 12th BiPC → BSc Microbiology → MSc Microbiology → PhD Medical Microbiology',
    submitterSkills: ['Laboratory techniques', 'Microscopy', 'Sterile techniques', 'Data analysis', 'Research methodology', 'Scientific writing'],
    submitterBackground: 'Urban',
    submitterEconomicStatus: 'Middle',
    isSeeded: true,
    stages: [
      { stageName: '10th Standard', education: '10th with good Science marks', skills: ['Basic Biology', 'Chemistry fundamentals', 'Scientific curiosity'], experience: 'School science projects', livingConditions: 'Home', helpReceived: 'Science teachers', suggestions: 'Develop interest in microscopic world. Read about Louis Pasteur and Koch.', ageRange: '14–15 years' },
      { stageName: '12th – BiPC Stream', education: '12th Biology, Physics, Chemistry', skills: ['Microbiology basics', 'Biochemistry', 'Organic Chemistry', 'Lab safety'], experience: 'Biology practicals, chemistry experiments', livingConditions: 'Home', helpReceived: 'School teachers, online resources', suggestions: 'Focus on Biology and Chemistry. Learn basic lab techniques.', ageRange: '16–17 years' },
      { stageName: 'BSc Microbiology', education: 'Bachelor of Science in Microbiology (3 years)', skills: ['Bacterial culture', 'Microscopy', 'Biochemical tests', 'Sterilization', 'Antibiotic sensitivity', 'Food microbiology'], experience: 'Lab practicals, industrial visits, mini-projects', livingConditions: 'College hostel', helpReceived: 'Microbiology faculty, lab technicians', suggestions: 'Master aseptic techniques. Participate in all lab sessions.', ageRange: '18–21 years' },
      { stageName: 'MSc Microbiology / Biotechnology', education: 'Master of Science in Microbiology or Medical Microbiology (2 years)', skills: ['Molecular biology', 'Immunology', 'Virology', 'Genetic engineering', 'Research design', 'Advanced lab techniques'], experience: 'Thesis work, research projects, hospital lab rotations', livingConditions: 'Hostel/research institute', helpReceived: 'Research guides, senior researchers, industry mentors', suggestions: 'Specialize in medical/industrial/food microbiology based on interest.', ageRange: '21–23 years' },
      { stageName: 'PhD / Research Microbiologist', education: 'PhD in Microbiology (3–5 years)', skills: ['Advanced research', 'Grant writing', 'Scientific publishing', 'Project management', 'Peer review'], experience: 'Original research, publications, conference presentations', livingConditions: 'Research institute accommodation', helpReceived: 'PhD supervisor, collaborators, funding agencies', suggestions: 'Focus on translational research with industry applications.', ageRange: '23–28 years' },
      { stageName: 'Senior Microbiologist / Lab Director', education: 'PhD + postdoctoral experience', skills: ['Quality control', 'Regulatory compliance', 'Team management', 'Consulting', 'Technology evaluation'], experience: 'Hospital labs, pharmaceutical companies, research institutions', livingConditions: 'Urban residence', helpReceived: 'Professional associations, industry networks', suggestions: 'Stay updated with latest diagnostic technologies and regulations.', ageRange: '28–35 years' },
    ],
    transitions: [
      { fromStage: '10th Standard', toStage: '12th – BiPC Stream', optionsAvailable: ['MPC', 'Commerce', 'Arts'], reasonChosen: 'BiPC provides foundation for microbiology and related fields.', mistakes: '', advice: 'Build strong foundation in Biology and Chemistry from early classes.' },
      { fromStage: '12th – BiPC Stream', toStage: 'BSc Microbiology', optionsAvailable: ['BSc Biotechnology', 'BSc Biochemistry', 'MBBS', 'B.Pharm'], reasonChosen: 'Microbiology degree offers diverse career options in healthcare and industry.', mistakes: 'Chose college without checking lab facilities.', advice: 'Visit microbiology labs during college selection. Check equipment and research facilities.' },
      { fromStage: 'BSc Microbiology', toStage: 'MSc Microbiology / Biotechnology', optionsAvailable: ['Direct lab technician jobs', 'Quality control positions', 'Teaching'], reasonChosen: 'Masters degree required for research and senior positions.', mistakes: 'Did not gain industry exposure during BSc.', advice: 'Do summer internships in pharmaceutical or food companies.' },
      { fromStage: 'MSc Microbiology / Biotechnology', toStage: 'PhD / Research Microbiologist', optionsAvailable: ['Industry R&D positions', 'Clinical lab management', 'Regulatory affairs'], reasonChosen: 'PhD enables independent research and academic positions.', mistakes: 'Chose research topic without considering market demand.', advice: 'Align research with industry needs (diagnostics, therapeutics, food safety).' },
      { fromStage: 'PhD / Research Microbiologist', toStage: 'Senior Microbiologist / Lab Director', optionsAvailable: ['Academic positions', 'International research', 'Entrepreneurship'], reasonChosen: 'Hospital lab director role offers stability and patient impact.', mistakes: 'Underestimated administrative responsibilities.', advice: 'Develop management and regulatory knowledge alongside technical expertise.' },
    ],
  },

  // ─── 13. PHARMACIST ───────────────────────────────────────────────────────────
  {
    title: 'Pharmacist',
    category: 'Medical',
    description: 'Dispense medications, provide drug information, and ensure safe medication use in healthcare settings.',
    submitterName: 'Anita Patel',
    submitterEmail: 'anita.patel@example.com',
    submitterGender: 'Female',
    submitterEducationHistory: '10th → 12th BiPC → D.Pharm → B.Pharm → Registered Pharmacist',
    submitterSkills: ['Drug knowledge', 'Patient counseling', 'Inventory management', 'Regulatory compliance', 'Clinical pharmacy', 'Communication'],
    submitterBackground: 'Urban',
    submitterEconomicStatus: 'Middle',
    isSeeded: true,
    stages: [
      { stageName: '10th Standard', education: '10th with Science subjects', skills: ['Basic Chemistry', 'Biology fundamentals', 'Mathematics'], experience: 'School science fairs', livingConditions: 'Home', helpReceived: 'Science teachers', suggestions: 'Develop interest in medicines and healthcare. Read about pharmaceutical discoveries.', ageRange: '14–15 years' },
      { stageName: '12th – BiPC Stream', education: '12th Biology, Physics, Chemistry', skills: ['Organic Chemistry', 'Human Physiology', 'Biochemistry', 'Pharmaceutical basics'], experience: 'Chemistry practicals, biology projects', livingConditions: 'Home', helpReceived: 'School teachers, pharmacy entrance coaching', suggestions: 'Focus on Chemistry and Biology. Prepare for pharmacy entrance exams.', ageRange: '16–17 years' },
      { stageName: 'D.Pharm (Diploma in Pharmacy)', education: 'Diploma in Pharmacy (2 years)', skills: ['Pharmaceutics', 'Pharmacology', 'Pharmaceutical Chemistry', 'Drug dispensing', 'Community pharmacy'], experience: 'Hospital pharmacy rotations, retail pharmacy training', livingConditions: 'College hostel or home', helpReceived: 'Pharmacy faculty, practicing pharmacists', suggestions: 'Learn drug names and their uses. Practice accurate dispensing.', ageRange: '17–19 years' },
      { stageName: 'B.Pharm (Bachelor of Pharmacy)', education: 'Bachelor of Pharmacy (4 years after 12th or 2 years after D.Pharm)', skills: ['Clinical pharmacy', 'Hospital pharmacy', 'Quality control', 'Drug information', 'Regulatory affairs'], experience: 'Hospital internships, industrial training, community pharmacy practice', livingConditions: 'College hostel', helpReceived: 'Clinical pharmacists, industry mentors', suggestions: 'Focus on clinical pharmacy and patient counseling skills.', ageRange: '19–23 years' },
      { stageName: 'Registered Pharmacist', education: 'B.Pharm + Pharmacy Council registration', skills: ['Patient counseling', 'Drug interactions', 'Therapeutic monitoring', 'Inventory management', 'Regulatory compliance'], experience: 'Retail pharmacy, hospital pharmacy, or pharmaceutical industry', livingConditions: 'Rented accommodation near workplace', helpReceived: 'Senior pharmacists, medical professionals', suggestions: 'Build trust with patients. Stay updated with new drugs and regulations.', ageRange: '23–26 years' },
      { stageName: 'Clinical Pharmacist / Pharmacy Manager', education: 'B.Pharm + additional certifications', skills: ['Clinical decision making', 'Team management', 'Quality assurance', 'Patient education', 'Research'], experience: 'Hospital clinical pharmacy, pharmacy management, specialized areas', livingConditions: 'Urban residence', helpReceived: 'Hospital administration, professional associations', suggestions: 'Pursue clinical pharmacy specialization. Consider M.Pharm for advancement.', ageRange: '26–32 years' },
    ],
    transitions: [
      { fromStage: '10th Standard', toStage: '12th – BiPC Stream', optionsAvailable: ['MPC', 'Commerce', 'Arts'], reasonChosen: 'BiPC provides foundation for pharmacy and medical sciences.', mistakes: '', advice: 'Maintain good grades in Chemistry and Biology for pharmacy entrance.' },
      { fromStage: '12th – BiPC Stream', toStage: 'D.Pharm (Diploma in Pharmacy)', optionsAvailable: ['B.Pharm directly', 'MBBS', 'B.Sc Nursing', 'Other paramedical'], reasonChosen: 'Diploma pharmacy is shorter route and provides practical experience early.', mistakes: 'Chose college without checking pharmacy practice facilities.', advice: 'Visit pharmacy colleges to check dispensing labs and hospital tie-ups.' },
      { fromStage: 'D.Pharm (Diploma in Pharmacy)', toStage: 'B.Pharm (Bachelor of Pharmacy)', optionsAvailable: ['Direct pharmacy jobs', 'Lateral entry to B.Pharm', 'Other diplomas'], reasonChosen: 'Bachelor degree opens more opportunities and higher positions.', mistakes: 'Did not pursue B.Pharm immediately after D.Pharm.', advice: 'Complete B.Pharm for better career prospects and salary.' },
      { fromStage: 'B.Pharm (Bachelor of Pharmacy)', toStage: 'Registered Pharmacist', optionsAvailable: ['Higher studies (M.Pharm)', 'Pharmaceutical industry', 'Drug inspector exams'], reasonChosen: 'Retail pharmacy provides direct patient interaction and business experience.', mistakes: 'Started with low salary expectations.', advice: 'Register with state pharmacy council immediately after graduation.' },
      { fromStage: 'Registered Pharmacist', toStage: 'Clinical Pharmacist / Pharmacy Manager', optionsAvailable: ['M.Pharm', 'MBA Healthcare', 'Drug regulatory positions'], reasonChosen: 'Hospital clinical pharmacy offers intellectual challenge and patient impact.', mistakes: 'Did not pursue additional certifications early.', advice: 'Get certified in clinical pharmacy. Consider M.Pharm for specialization.' },
    ],
  },

  // ─── 14. BIOTECHNOLOGY RESEARCHER ─────────────────────────────────────────────
  {
    title: 'Biotechnology Researcher',
    category: 'Medical',
    description: 'Conduct research in biotechnology applications including genetic engineering, drug development, and bioinformatics.',
    submitterName: 'Dr. Karan Mehta',
    submitterEmail: 'karan.mehta@example.com',
    submitterGender: 'Male',
    submitterEducationHistory: '10th → 12th BiPC → BSc Biotechnology → MSc Biotechnology → PhD Biotechnology',
    submitterSkills: ['Molecular biology', 'Genetic engineering', 'Bioinformatics', 'Lab techniques', 'Research methodology', 'Scientific writing'],
    submitterBackground: 'Urban',
    submitterEconomicStatus: 'Rich',
    isSeeded: true,
    stages: [
      { stageName: '10th Standard', education: '10th with strong Science performance', skills: ['Biology basics', 'Chemistry fundamentals', 'Scientific thinking'], experience: 'Science projects, biology experiments', livingConditions: 'Home', helpReceived: 'Science teachers, parents', suggestions: 'Read about genetic engineering and biotechnology breakthroughs.', ageRange: '14–15 years' },
      { stageName: '12th – BiPC Stream', education: '12th Biology, Physics, Chemistry', skills: ['Biochemistry', 'Molecular Biology basics', 'Organic Chemistry', 'Biotechnology awareness'], experience: 'Biology practicals, science exhibitions', livingConditions: 'Home', helpReceived: 'School teachers, online biotech resources', suggestions: 'Focus on Biology and Chemistry. Learn about DNA, proteins, and enzymes.', ageRange: '16–17 years' },
      { stageName: 'BSc Biotechnology / Microbiology', education: 'Bachelor of Science in Biotechnology (3 years)', skills: ['Molecular cloning', 'PCR techniques', 'Cell culture', 'Microbial techniques', 'Biochemistry assays', 'Instrumentation'], experience: 'Lab practicals, mini-research projects, industrial visits', livingConditions: 'College hostel', helpReceived: 'Biotech faculty, lab technicians, industry experts', suggestions: 'Master basic lab techniques. Participate in biotech competitions.', ageRange: '18–21 years' },
      { stageName: 'MSc Biotechnology / Biochemistry', education: 'Master of Science in Biotechnology (2 years)', skills: ['Advanced molecular biology', 'Genetic engineering', 'Bioinformatics', 'Protein purification', 'Tissue culture', 'Research design'], experience: 'Thesis research, internships in biotech companies, conference presentations', livingConditions: 'Hostel/research institute', helpReceived: 'Research supervisors, senior scientists, industry mentors', suggestions: 'Choose specialization (medical biotech, agricultural biotech, industrial biotech).', ageRange: '21–23 years' },
      { stageName: 'PhD Biotechnology', education: 'PhD in Biotechnology or related field (3–5 years)', skills: ['Independent research', 'Grant writing', 'Scientific publishing', 'Advanced techniques', 'Project management'], experience: 'Original research, publications, patent applications, collaborations', livingConditions: 'Research institute accommodation', helpReceived: 'PhD guide, research collaborators, funding agencies', suggestions: 'Focus on translational research with commercial applications.', ageRange: '23–28 years' },
      { stageName: 'Senior Biotechnology Researcher / Scientist', education: 'PhD + postdoctoral experience', skills: ['Research leadership', 'Technology transfer', 'Regulatory affairs', 'Business development', 'Mentoring'], experience: 'R&D leadership, product development, consulting, academic positions', livingConditions: 'Urban residence', helpReceived: 'Industry networks, professional associations, venture capitalists', suggestions: 'Bridge gap between research and commercialization. Stay updated with biotech regulations.', ageRange: '28–35 years' },
    ],
    transitions: [
      { fromStage: '10th Standard', toStage: '12th – BiPC Stream', optionsAvailable: ['MPC', 'Commerce', 'Arts'], reasonChosen: 'BiPC provides essential foundation for biotechnology.', mistakes: '', advice: 'Build strong foundation in Biology and Chemistry from early classes.' },
      { fromStage: '12th – BiPC Stream', toStage: 'BSc Biotechnology / Microbiology', optionsAvailable: ['BSc Biochemistry', 'BSc Genetics', 'MBBS', 'B.Pharm'], reasonChosen: 'Biotechnology degree offers interdisciplinary knowledge and diverse career options.', mistakes: 'Chose college without checking research facilities.', advice: 'Visit biotech labs during college selection. Check industry collaborations.' },
      { fromStage: 'BSc Biotechnology / Microbiology', toStage: 'MSc Biotechnology / Biochemistry', optionsAvailable: ['Direct biotech industry jobs', 'Research assistant positions', 'Teaching'], reasonChosen: 'Masters degree essential for research positions and PhD.', mistakes: 'Did not gain sufficient lab experience during BSc.', advice: 'Do summer research internships. Build publication record from BSc projects.' },
      { fromStage: 'MSc Biotechnology / Biochemistry', toStage: 'PhD Biotechnology', optionsAvailable: ['Industry R&D positions', 'Clinical research', 'Regulatory affairs'], reasonChosen: 'PhD enables independent research and leadership positions.', mistakes: 'Chose research topic without considering funding and market relevance.', advice: 'Apply for research fellowships. Network with potential PhD guides early.' },
      { fromStage: 'PhD Biotechnology', toStage: 'Senior Biotechnology Researcher / Scientist', optionsAvailable: ['Academic positions', 'Biotech entrepreneurship', 'Consulting'], reasonChosen: 'Industry R&D offers better compensation and faster career growth.', mistakes: 'Underestimated business development aspects.', advice: 'Learn about IP, regulatory affairs, and business development alongside research.' },
    ],
  },

  // ─── 15. FORENSIC SCIENTIST ───────────────────────────────────────────────────
  {
    title: 'Forensic Scientist',
    category: 'Medical',
    description: 'Apply scientific methods to investigate crimes, analyze evidence, and provide expert testimony in legal proceedings.',
    submitterName: 'Dr. Meera Joshi',
    submitterEmail: 'meera.joshi@example.com',
    submitterGender: 'Female',
    submitterEducationHistory: '10th → 12th BiPC → BSc Forensic Science → MSc Forensic Science → Forensic Specialist',
    submitterSkills: ['Evidence analysis', 'Crime scene investigation', 'Laboratory techniques', 'Legal knowledge', 'Report writing', 'Court testimony'],
    submitterBackground: 'Urban',
    submitterEconomicStatus: 'Middle',
    isSeeded: true,
    stages: [
      { stageName: '10th Standard', education: '10th with interest in Science and investigation', skills: ['Biology basics', 'Chemistry fundamentals', 'Observation skills', 'Logical reasoning'], experience: 'Science projects, mystery solving activities', livingConditions: 'Home', helpReceived: 'Science teachers, detective novels', suggestions: 'Develop analytical thinking. Read about famous criminal cases and forensic breakthroughs.', ageRange: '14–15 years' },
      { stageName: '12th – BiPC Stream', education: '12th Biology, Physics, Chemistry', skills: ['Human Biology', 'Organic Chemistry', 'Toxicology basics', 'Crime scene awareness'], experience: 'Biology practicals, chemistry experiments', livingConditions: 'Home', helpReceived: 'School teachers, forensic science documentaries', suggestions: 'Focus on Biology and Chemistry. Learn about poisons and their effects.', ageRange: '16–17 years' },
      { stageName: 'BSc Forensic Science / Criminology', education: 'Bachelor of Science in Forensic Science (3 years)', skills: ['Crime scene photography', 'Fingerprint analysis', 'DNA extraction', 'Toxicology', 'Ballistics', 'Questioned documents'], experience: 'Lab practicals, mock crime scenes, court visits', livingConditions: 'College hostel', helpReceived: 'Forensic faculty, police officers, lab technicians', suggestions: 'Master evidence collection and preservation techniques.', ageRange: '18–21 years' },
      { stageName: 'MSc Forensic Science / Criminology', education: 'Master of Science in Forensic Science (2 years)', skills: ['Advanced DNA analysis', 'Digital forensics', 'Forensic pathology', 'Crime pattern analysis', 'Research methodology'], experience: 'Thesis work, forensic lab internships, court testimony practice', livingConditions: 'Hostel/research institute', helpReceived: 'Forensic experts, research supervisors, law enforcement', suggestions: 'Specialize in one area (DNA, toxicology, cyber forensics, etc.).', ageRange: '21–23 years' },
      { stageName: 'Forensic Scientist / Analyst', education: 'MSc + forensic certification', skills: ['Evidence examination', 'Chain of custody', 'Report writing', 'Court preparation', 'Quality assurance'], experience: 'Government forensic labs, private forensic companies, police departments', livingConditions: 'Urban residence near workplace', helpReceived: 'Senior forensic scientists, legal experts, professional associations', suggestions: 'Maintain objectivity and scientific rigor in all investigations.', ageRange: '23–28 years' },
      { stageName: 'Senior Forensic Scientist / Lab Director', education: 'MSc + advanced certifications + experience', skills: ['Lab management', 'Quality control', 'Training', 'Policy development', 'Expert testimony', 'Research'], experience: 'Leadership in forensic labs, accreditation management, international collaborations', livingConditions: 'Urban residence', helpReceived: 'Government agencies, international forensic organizations', suggestions: 'Stay updated with latest forensic technologies and legal developments.', ageRange: '28–35 years' },
    ],
    transitions: [
      { fromStage: '10th Standard', toStage: '12th – BiPC Stream', optionsAvailable: ['MPC', 'Commerce', 'Arts'], reasonChosen: 'BiPC provides scientific foundation for forensic science.', mistakes: '', advice: 'Develop strong analytical and observation skills from early age.' },
      { fromStage: '12th – BiPC Stream', toStage: 'BSc Forensic Science / Criminology', optionsAvailable: ['BSc Chemistry', 'BSc Biology', 'LLB', 'Police training'], reasonChosen: 'Forensic science degree provides specialized training in crime investigation.', mistakes: 'Chose college without checking forensic lab facilities.', advice: 'Visit forensic science colleges to check labs and police collaborations.' },
      { fromStage: 'BSc Forensic Science / Criminology', toStage: 'MSc Forensic Science / Criminology', optionsAvailable: ['Direct forensic lab jobs', 'Police investigation', 'Security services'], reasonChosen: 'Masters degree required for senior forensic positions.', mistakes: 'Did not gain practical forensic experience during BSc.', advice: 'Intern at forensic labs or police crime labs during vacations.' },
      { fromStage: 'MSc Forensic Science / Criminology', toStage: 'Forensic Scientist / Analyst', optionsAvailable: ['Research positions', 'Teaching forensic science', 'Private investigation'], reasonChosen: 'Government forensic lab offers job security and diverse case exposure.', mistakes: 'Underestimated the psychological impact of crime scene work.', advice: 'Develop coping mechanisms for dealing with sensitive cases.' },
      { fromStage: 'Forensic Scientist / Analyst', toStage: 'Senior Forensic Scientist / Lab Director', optionsAvailable: ['International forensic organizations', 'Consulting', 'Academia'], reasonChosen: 'Lab director position allows shaping forensic science practices.', mistakes: 'Did not pursue management training early.', advice: 'Develop leadership and administrative skills alongside technical expertise.' },
    ],
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('Connected to MongoDB');

    let insertedCount = 0;
    let updatedCount = 0;

    for (const cp of careerPaths) {
      const existing = await CareerPath.findOne({ title: cp.title, isSeeded: true });
      if (existing) {
        const preservedStatus = existing.status || cp.status || 'pending';
        await CareerPath.findByIdAndUpdate(
          existing._id,
          { ...cp, status: preservedStatus },
          { new: true, runValidators: true }
        );
        updatedCount += 1;
      } else {
        await CareerPath.create(cp);
        insertedCount += 1;
      }
    }

    console.log(`Inserted ${insertedCount} new seeded career paths`);
    console.log(`Updated ${updatedCount} existing seeded career paths`);

    await mongoose.disconnect();
    console.log('Done. MongoDB disconnected.');
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err.message);
    process.exit(1);
  }
}

seed();
